name: ci

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'Base Node image'
        required: true
        default: '20-alpine'
      version:
        description: 'Vercel version'
        required: false
        default: 'latest'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERCEL_VERSION=${{ github.event.inputs.version }}
            BASE_IMAGE=${{ github.event.inputs.base_image }}
          push: true
          tags: ${{ vars.DOCKER_IMAGE_NAME }}:latest
